### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [aubreypwd/zsh-plugin-vcshr#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by aubreypwd** [comment]
I will try and get this done soon too, just letting you know I've seen this!

**Comment by unixorn** [comment]
Thanks! Either comment here and I'll add it or you can add a PR yourself, whatever's easier for you.

**Comment by aubreypwd** [comment]
Just so you know, this is still on my list! I just haven't had time to get around to it.

**Comment by unixorn** [comment]
No problem, I'll add it once you close this issue.
